library(stringr)
library(hrbrthemes)
library(reshape2)
library(hashmap)

source('source/utils/files.r')
source('source/utils/manifest-operations.r')
source('source/utils/dataframe.r')

source('source/visualizers/line.r')
source('source/visualizers/histogram.r')
source('source/visualizers/3d-accumulative-mesh.r')
source('source/visualizers/3d-histogram.r')

read <- function(path) {
    manifest <- read_manifest(path)
    data <- read_corpus_data(path, manifest)
    kind <- get_property_value(manifest, 'kind', 'line')
    return(
        list(manifest = manifest, data = data$data, index_column_name = data$index_column_name, kind = kind)
    )
}

render <- function(corpus) {
    kind <- corpus$kind
    
    if (kind == 'line') {
        plot <- visualize_as_line(corpus)
    } else if(kind == "histogram") {
        plot <- visualize_as_histogram(corpus)
    } else if(kind == "3d-accumulative-mesh"){
        plot <- visualize_as_mesh(corpus)
    } else if(kind == "3d-histogram"){
        plot <- visualize_as_3d_histogram(corpus)
    }
    
    corpus$plot <- plot
    return(corpus)
}

draw <- function(corpus, path) {
    kind <- corpus$kind

    if (kind == 'line' | kind == 'histogram') {
        ggsave(path, height = 7 , width = 14)
    } else if (kind=="3d-accumulative-mesh" | kind == '3d-histogram') {
        orca(corpus$plot, path, error=F)
        file.rename(from = str_replace(path, ".jpeg", '_1.jpeg'),  to = path) # fix names for files generated by plotly
    }
}

visualize_corpus <- function(path, images_path) {
    # Generate image path

    folder_path <- get_last_path_element(path)
    image_path <- paste(images_path, "/", folder_path, ".jpeg", sep = "")
    create_folder_if_doesnt_exist(images_path)

    # Generate manifest path and read the data

    path %>% read %>% render %>% draw(image_path)

    return(image_path)
}
