source('source/utils/files.r')
source('source/utils/manifest-operations.r')
source('source/utils/dataframe.r')

source('source/visualizers/line.r')
source('source/visualizers/histogram.r')
source('source/visualizers/mesh.r')

read_corpus <- function(path) {
    manifest <- read_manifest(path)
    data <- read_corpus_data(path, manifest)
    return(
        list(manifest = manifest, data = data$data, index_column_name = data$index_column_name)
    )
}

visualize_corpus <- function(path, images_path) {
    library(stringr)
    library(hrbrthemes)
    library(reshape2)
    library(hashmap)

    # Generate image path

    folder_path <- get_parent_folder_path(path)
    image_path <- paste(images_path, "/", folder_path, ".jpeg", sep = "")
    create_folder_if_doesnt_exist(images_path)

    # Generate manifest path and read the data

    corpus <- read_corpus(path)
    data <- corpus$data

    # Melt dataframe using it's index column as an anchor point, group values if required

    plot_kind <- get_property_value(corpus$manifest, 'kind', 'line')

    # Draw the plot and save it on the disk

    if (plot_kind=='line') {
        visualize_as_line(corpus)
        ggsave(image_path, height = 7 , width = 14)
    } else if(plot_kind=="histogram") {
        visualize_as_histogram(corpus)
        ggsave(image_path, height = 7 , width = 14)
    } else if(plot_kind=="mesh"){
        fig <- visualize_as_mesh(corpus)
        orca(fig, image_path, error=F)
        file.rename(from = str_replace(image_path, ".jpeg", '_1.jpeg'),  to = image_path) # fix names for files generated by plotly
    }

    return(image_path)
}
